services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
    environment:
      - LS_LOG=info
      - DYNAMODB_IN_MEMORY=1
      - EXTENSION_AUTO_INSTALL=sqs-admin

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack

  sqs-browser:
    image: pacovk/sqs-admin
    container_name: sqs-browser
    ports:
      - "8011:8011"
    environment:
      - HTTP_PORT=8011
      - SQS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack
