services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
    environment:
      - LS_LOG=debug
      - DYNAMODB_IN_MEMORY=1
      - SERVICES=apigateway,cloudformation,cloudwatch,dynamodb,dynamodbstreams,events,iam,kinesis,lambda,logs,s3,sqs,sts

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack

  sqs-browser:
    image: pacovk/sqs-admin
    container_name: sqs-browser
    ports:
      - "8002:3999"
    environment:
      - SQS_ENDPOINT_URL=http://localstack:4566
      - SQS_AWS_REGION=us-east-1
    depends_on:
      - localstack

  s3-browser:
    image: cloudlena/s3manager
    container_name: s3-browser
    ports:
      - "8003:8080"
    environment:
      - ENDPOINT=localstack:4566
      - ACCESS_KEY_ID=test
      - SECRET_ACCESS_KEY=test
      - USE_SSL=false
    depends_on:
      - localstack
